language: go

go:
  - 1.9
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get -t ./...

script:
  - go build -v ./examples/base/main.go
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci